/**
 * Auto-generated by scripts/generate-manga-assets.js
 */
import type { ImageSourcePropType } from 'react-native';

type AssetMap = Record<string, ImageSourcePropType>;
type CbzMap = Record<string, number>;

const COVERS: AssetMap = {
  'Bakemonogatari|BAKEMONOGATARI v01 (2019) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v01 (2019) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v02 (2020) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v02 (2020) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v03 (2020) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v03 (2020) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v04 (2020) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v04 (2020) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v05 (2020) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v05 (2020) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v06 (2020) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v06 (2020) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v07 (2021) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v07 (2021) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v08 (2021) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v08 (2021) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v09 (2021) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v09 (2021) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v10 (2021) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v10 (2021) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v11 (2021) (Digital) (1r0n) (f2).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v11 (2021) (Digital) (1r0n) (f2).webp'),
  'Bakemonogatari|BAKEMONOGATARI v12 (2021) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v12 (2021) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v13 (2022) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v13 (2022) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v14 (2022) (Digital) (1r0n) (f2).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v14 (2022) (Digital) (1r0n) (f2).webp'),
  'Bakemonogatari|BAKEMONOGATARI v15 (2022) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v15 (2022) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v16 (2022) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v16 (2022) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v17 (2023) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v17 (2023) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v18 (2023) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v18 (2023) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v19 (2023) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v19 (2023) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v20 (2023) (Digital) (1r0n).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v20 (2023) (Digital) (1r0n).webp'),
  'Bakemonogatari|BAKEMONOGATARI v21 (2024) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v21 (2024) (Digital) (1r0n) (f).webp'),
  'Bakemonogatari|BAKEMONOGATARI v22 (2024) (Digital) (1r0n) (f).webp': require('./Bakemonogatari/manga covers/BAKEMONOGATARI v22 (2024) (Digital) (1r0n) (f).webp'),
  'Cipher Academy|Volume 1.jpg': require('./Cipher Academy/Volume 1.jpg'),
  'Cipher Academy|Volume 2.jpg': require('./Cipher Academy/Volume 2.jpg'),
  'Cipher Academy|Volume 3.jpg': require('./Cipher Academy/Volume 3.jpg'),
  'Cipher Academy|Volume 4.jpg': require('./Cipher Academy/Volume 4.jpg'),
  'Cipher Academy|Volume 5.jpg': require('./Cipher Academy/Volume 5.jpg'),
  'Cipher Academy|Volume 6.jpg': require('./Cipher Academy/Volume 6.jpg'),
  'Cipher Academy|Volume 7.jpg': require('./Cipher Academy/Volume 7.jpg'),
};

const CBZ: CbzMap = {
};

function key(folder: string, filename: string) {
  return `${folder}|${filename}`;
}

export function getMangaCoverSource(folder: string, coverFilename: string): ImageSourcePropType | null {
  return COVERS[key(folder, coverFilename)] ?? null;
}

export function getCbzRequire(folder: string, cbzFilename: string): number | null {
  return CBZ[key(folder, cbzFilename)] ?? null;
}
