/**
 * Auto-generated by scripts/generate-lightnovel-assets.js
 * Maps (seriesFolder, filename) to bundled cover/PDF assets.
 */
import type { ImageSourcePropType } from 'react-native';

type AssetMap = Record<string, ImageSourcePropType>;
type PdfMap = Record<string, number>;

const COVERS: AssetMap = {
  'Boukyako Tantei Series|The Forgetful Detective v01.webp': require('./Boukyako Tantei Series/Novel Covers/The Forgetful Detective v01.webp'),
  'Boukyako Tantei Series|The Forgetful Detective v02.webp': require('./Boukyako Tantei Series/Novel Covers/The Forgetful Detective v02.webp'),
  'Boukyako Tantei Series|The Forgetful Detective v03.webp': require('./Boukyako Tantei Series/Novel Covers/The Forgetful Detective v03.webp'),
  'Boukyako Tantei Series|The Forgetful Detective v04.webp': require('./Boukyako Tantei Series/Novel Covers/The Forgetful Detective v04.webp'),
  'Boukyako Tantei Series|The Forgetful Detective v05.webp': require('./Boukyako Tantei Series/Novel Covers/The Forgetful Detective v05.webp'),
  'Monogatari Series|Monogatari Series v01 - BAKEMONOGATARI Part 1 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v01 - BAKEMONOGATARI Part 1 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v02 - BAKEMONOGATARI Part 2 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v02 - BAKEMONOGATARI Part 2 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v03 - BAKEMONOGATARI Part 3 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v03 - BAKEMONOGATARI Part 3 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v04 - KIZUMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v04 - KIZUMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v05 - NISEMONOGATARI Part 1 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v05 - NISEMONOGATARI Part 1 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v06 - NISEMONOGATARI Part 2 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v06 - NISEMONOGATARI Part 2 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v07 - NEKOMONOGATARI (BLACK) [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v07 - NEKOMONOGATARI (BLACK) [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v08 - NEKOMONOGATARI (WHITE) [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v08 - NEKOMONOGATARI (WHITE) [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v09 - KABUKIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v09 - KABUKIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v10 - HANAMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v10 - HANAMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v11 - OTORIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v11 - OTORIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v12 - ONIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v12 - ONIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v13 - KOIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v13 - KOIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v14 - TSUKIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v14 - TSUKIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v15 - KOYOMIMONOGATARI Part 1 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v15 - KOYOMIMONOGATARI Part 1 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v16 - KOYOMIMONOGATARI Part 2 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v16 - KOYOMIMONOGATARI Part 2 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v17 - OWARIMONOGATARI Part 1 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v17 - OWARIMONOGATARI Part 1 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v18 - OWARIMONOGATARI Part 2 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v18 - OWARIMONOGATARI Part 2 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v19 - OWARIMONOGATARI Part 3 [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v19 - OWARIMONOGATARI Part 3 [Vertical] [LuCaZ].webp'),
  'Monogatari Series|Monogatari Series v20 - ZOKU OWARIMONOGATARI [Vertical] [LuCaZ].webp': require('./Monogatari Series/Novel Covers/Monogatari Series v20 - ZOKU OWARIMONOGATARI [Vertical] [LuCaZ].webp'),
  'Sekai Series|Volume 1 - Our Broken World.webp': require('./Sekai Series/Novel Covers/Volume 1 - Our Broken World.webp'),
  'Sekai Series|Volume 2 - Our Eerie and Artless Enclosed World - Nisio Isin.webp': require('./Sekai Series/Novel Covers/Volume 2 - Our Eerie and Artless Enclosed World - Nisio Isin.webp'),
  'Sekai Series|Volume 3 - The World We Broke.webp': require('./Sekai Series/Novel Covers/Volume 3 - The World We Broke.webp'),
  'Sekai Series|Volume 4 - Our Eerie and Artless Enclosed Broken World.webp': require('./Sekai Series/Novel Covers/Volume 4 - Our Eerie and Artless Enclosed Broken World.webp'),
  'Zaregoto Series|Zaregoto Series v01 - Decapitation [Vertical] [LuCaZ].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v01 - Decapitation [Vertical] [LuCaZ].webp'),
  'Zaregoto Series|Zaregoto Series v02 - Strangulation [Vertical] [LuCaZ].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v02 - Strangulation [Vertical] [LuCaZ].webp'),
  'Zaregoto Series|Zaregoto Series v03 - Suspension [Vertical] [LuCaZ].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v03 - Suspension [Vertical] [LuCaZ].webp'),
  'Zaregoto Series|Zaregoto Series v04 - Psycho Logical [DutchAngleTL].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v04 - Psycho Logical [DutchAngleTL].webp'),
  'Zaregoto Series|Zaregoto Series v05 - Psycho Logical 2 [DutchAngleTL].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v05 - Psycho Logical 2 [DutchAngleTL].webp'),
  'Zaregoto Series|Zaregoto Series v07 - Nekosogi Radical 1 [SwayTL].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v07 - Nekosogi Radical 1 [SwayTL].webp'),
  'Zaregoto Series|Zaregoto Series v08 - Nekosogi Radical 2 [SwayTL].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v08 - Nekosogi Radical 2 [SwayTL].webp'),
  'Zaregoto Series|Zaregoto Series v09 - Nekosogi Radical 3 [SwayTL].webp': require('./Zaregoto Series/Novel Covers/Zaregoto Series v09 - Nekosogi Radical 3 [SwayTL].webp'),
};

const PDFS: PdfMap = {
  'Boukyako Tantei Series|The Forgetful Detective v01.pdf': require('./Boukyako Tantei Series/The Forgetful Detective v01.pdf'),
  'Boukyako Tantei Series|The Forgetful Detective v02.pdf': require('./Boukyako Tantei Series/The Forgetful Detective v02.pdf'),
  'Boukyako Tantei Series|The Forgetful Detective v03.pdf': require('./Boukyako Tantei Series/The Forgetful Detective v03.pdf'),
  'Boukyako Tantei Series|The Forgetful Detective v04.pdf': require('./Boukyako Tantei Series/The Forgetful Detective v04.pdf'),
  'Boukyako Tantei Series|The Forgetful Detective v05.pdf': require('./Boukyako Tantei Series/The Forgetful Detective v05.pdf'),
  'Monogatari Series|Monogatari Series v01 - BAKEMONOGATARI Part 1 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v01 - BAKEMONOGATARI Part 1 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v02 - BAKEMONOGATARI Part 2 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v02 - BAKEMONOGATARI Part 2 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v03 - BAKEMONOGATARI Part 3 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v03 - BAKEMONOGATARI Part 3 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v04 - KIZUMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v04 - KIZUMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v05 - NISEMONOGATARI Part 1 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v05 - NISEMONOGATARI Part 1 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v06 - NISEMONOGATARI Part 2 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v06 - NISEMONOGATARI Part 2 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v07 - NEKOMONOGATARI (BLACK) [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v07 - NEKOMONOGATARI (BLACK) [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v08 - NEKOMONOGATARI (WHITE) [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v08 - NEKOMONOGATARI (WHITE) [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v09 - KABUKIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v09 - KABUKIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v10 - HANAMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v10 - HANAMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v11 - OTORIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v11 - OTORIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v12 - ONIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v12 - ONIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v13 - KOIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v13 - KOIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v14 - TSUKIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v14 - TSUKIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v15 - KOYOMIMONOGATARI Part 1 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v15 - KOYOMIMONOGATARI Part 1 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v16 - KOYOMIMONOGATARI Part 2 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v16 - KOYOMIMONOGATARI Part 2 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v17 - OWARIMONOGATARI Part 1 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v17 - OWARIMONOGATARI Part 1 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v18 - OWARIMONOGATARI Part 2 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v18 - OWARIMONOGATARI Part 2 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v19 - OWARIMONOGATARI Part 3 [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v19 - OWARIMONOGATARI Part 3 [Vertical] [LuCaZ].pdf'),
  'Monogatari Series|Monogatari Series v20 - ZOKU OWARIMONOGATARI [Vertical] [LuCaZ].pdf': require('./Monogatari Series/Monogatari Series v20 - ZOKU OWARIMONOGATARI [Vertical] [LuCaZ].pdf'),
  'Sekai Series|Volume 1 - Our Broken World.pdf': require('./Sekai Series/Volume 1 - Our Broken World.pdf'),
  'Sekai Series|Volume 2 - Our Eerie and Artless Enclosed World - Nisio Isin.pdf': require('./Sekai Series/Volume 2 - Our Eerie and Artless Enclosed World - Nisio Isin.pdf'),
  'Sekai Series|Volume 3 - The World We Broke.pdf': require('./Sekai Series/Volume 3 - The World We Broke.pdf'),
  'Sekai Series|Volume 4 - Our Eerie and Artless Enclosed Broken World.pdf': require('./Sekai Series/Volume 4 - Our Eerie and Artless Enclosed Broken World.pdf'),
  'Zaregoto Series|Zaregoto Series v01 - Decapitation [Vertical] [LuCaZ].pdf': require('./Zaregoto Series/Zaregoto Series v01 - Decapitation [Vertical] [LuCaZ].pdf'),
  'Zaregoto Series|Zaregoto Series v02 - Strangulation [Vertical] [LuCaZ].pdf': require('./Zaregoto Series/Zaregoto Series v02 - Strangulation [Vertical] [LuCaZ].pdf'),
  'Zaregoto Series|Zaregoto Series v03 - Suspension [Vertical] [LuCaZ].pdf': require('./Zaregoto Series/Zaregoto Series v03 - Suspension [Vertical] [LuCaZ].pdf'),
  'Zaregoto Series|Zaregoto Series v04 - Psycho Logical [DutchAngleTL].pdf': require('./Zaregoto Series/Zaregoto Series v04 - Psycho Logical [DutchAngleTL].pdf'),
  'Zaregoto Series|Zaregoto Series v05 - Psycho Logical 2 [DutchAngleTL].pdf': require('./Zaregoto Series/Zaregoto Series v05 - Psycho Logical 2 [DutchAngleTL].pdf'),
  'Zaregoto Series|Zaregoto Series v06 - Hitokui Magical [Suiminchuudoku, SwayTL].pdf': require('./Zaregoto Series/Zaregoto Series v06 - Hitokui Magical [Suiminchuudoku, SwayTL].pdf'),
  'Zaregoto Series|Zaregoto Series v07 - Nekosogi Radical 1 [SwayTL].pdf': require('./Zaregoto Series/Zaregoto Series v07 - Nekosogi Radical 1 [SwayTL].pdf'),
  'Zaregoto Series|Zaregoto Series v08 - Nekosogi Radical 2 [SwayTL].pdf': require('./Zaregoto Series/Zaregoto Series v08 - Nekosogi Radical 2 [SwayTL].pdf'),
  'Zaregoto Series|Zaregoto Series v09 - Nekosogi Radical 3 [SwayTL].pdf': require('./Zaregoto Series/Zaregoto Series v09 - Nekosogi Radical 3 [SwayTL].pdf'),
};

function key(folder: string, filename: string): string {
  return `${folder}|${filename}`;
}

export function getCoverSource(folder: string, coverFilename: string): ImageSourcePropType | null {
  return COVERS[key(folder, coverFilename)] ?? null;
}

export function getPdfRequire(folder: string, pdfFilename: string): number | null {
  return PDFS[key(folder, pdfFilename)] ?? null;
}
